name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
        
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.9.1'
        cache: 'yarn'
    - run: yarn install --dev
    - run: yarn build
    - uses: actions/upload-artifact@v2
      with:
        name: openapi-explorer
        path: public
