name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16.9.1'
          cache: 'yarn'
      - name: Build
        run: |
          yarn install --dev
          yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: openapi-explorer
          path: public
